# Generated by Django 4.0.8 on 2022-11-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbpeople',
            name='phonePeople',
            field=models.BigIntegerField(db_column='phonePeople'),
        ),
    ]
